web:
  build: .
  volumes:
    - .:/app:rw
  links:
    - "mongo:mongo"
  ports:
    - "8080:8080"
  environment:
    - ESRI=http://services5.arcgis.com/g71O2CiScDdrYMx5/ArcGIS/rest/services/Bike_Test/FeatureServer/0/addFeatures
  restart: always

mongo:
  image: tutum/mongodb
  environment:
    - AUTH=no
  restart: always